/** The companion website. Two things now point at it — the Import/Export tab's outbound link and
 *  the in-app studio library, which fetches its manifest — so the origin lives in one place rather
 *  than being spelled out at each call site. */
export const SITE_ORIGIN = 'https://setupsheethelper.julianro.se'

/** The human-facing archive, opened in the user's browser. */
export const STUDIO_DOWNLOADS_URL = `${SITE_ORIGIN}/studio-downloads.html`

/** The machine-readable index the app fetches. Generated by the site's tools/build-manifest.mjs,
 *  and each entry's `file` is a path relative to SITE_ORIGIN. */
export const STUDIO_LIBRARY_INDEX_URL = `${SITE_ORIGIN}/studios/index.json`
